### ISSUE TITLE
ArgumentNullException @ ComboGestureCompilerEditor [1.3.0]

### ISSUE THREAD

**Issue by Nanabell** [hai-vr/combo-gesture-expressions-av3#143]
Hey,
firstly thank you for making this awesome tool :)

With the latest release (1.3.0) i've encountered an issue when creating an empty/new ComboGestureCompiler 
![image](https://user-images.githubusercontent.com/13600006/97442781-81af4400-192a-11eb-812a-5a2d02846ab2.png)

With this im unable to configure anything in the Compiler, to use the Compiler i added a null check even though i have no clue what implications this has 😂 but it works and thus far i havent seen anything break
![image](https://user-images.githubusercontent.com/13600006/97443015-c6d37600-192a-11eb-948c-9f4fc18cf49c.png)

or maybe this is just me being an idiot but i hope this helps.

**Comment by hai-vr** [comment]
Hello!

Thanks a lot for the issue report, I'll try to publish a release when I get some free time
