### ISSUE TITLE
Is the VCC release available yet?

### ISSUE THREAD

**Issue by Waterspark63** [hai-vr/combo-gesture-expressions-av3#367]
Just the title, I attempted to add the package.json in 'Packages/dev.hai-vr.cge/package.json' to VCC, and it errors out with the following:

Failed to load repository data from https://github.com/hai-vr/combo-gesture-expressions-av3/blob/main/Packages/dev.hai-vr.cge/package.json. The URL is invalid or does not contain a valid repository listing.

Is it not ready yet, or am I doing it wrong?

**Comment by hai-vr** [comment]
Hi, please follow this documentation page to install the VCC listing:
- https://docs.hai-vr.dev/docs/products/combo-gesture-expressions/v3.0-vcc

**Comment by Waterspark63** [comment]
Ah, so I was doing it wrong, thank you!
